In [ ]:
import numpy as np

In [3]:
##Numpy examples
#creating array
arr=np.array([1,2,3,4,5])
matrix=np.array([[1,2,3],[4,5,6]])

##Vectorized operations (No loops needed)
arr_squared=arr**2 
arr_sum=arr + 10
# Matrix operations (core of ML)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)  # Matrix multiplication

# Statistical operations
mean = np.mean(arr)  # 3.0
std = np.std(arr)    # 1.414...

# Useful array creation
zeros = np.zeros((3, 3))      # 3x3 matrix of zeros
ones = np.ones((2, 4))        # 2x4 matrix of ones
random = np.random.rand(5)    # 5 random numbers [0, 1)


In [4]:
print("Array:", arr)
print("Matrix:\n", matrix)
print("Squared Array:", arr_squared)
print("Array + 10:", arr_sum)
print("Dot Product:\n", dot_product)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random Numbers:", random)


Array: [1 2 3 4 5]
Matrix:
 [[1 2 3]
 [4 5 6]]
Squared Array: [ 1  4  9 16 25]
Array + 10: [11 12 13 14 15]
Dot Product:
 [[19 22]
 [43 50]]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Numbers: [0.7799307  0.49749019 0.33267289 0.98603474 0.04202903]


In [ ]:
import pandas as pd 

In [5]:
# Creating DataFrames
data = {
    'age': [25, 30, 35, 40],
    'salary': [50000, 60000, 70000, 80000],
    'city': ['NYC', 'SF', 'LA', 'NYC']
}
df = pd.DataFrame(data)

# Reading data (most common in real projects)
# df = pd.read_csv('data.csv')

# Basic exploration
print(df.head())        # First 5 rows
print(df.info())        # Data types, null counts
print(df.describe())    # Statistics for numerical columns

# Selecting data
ages = df['age']                    # Single column
subset = df[['age', 'salary']]      # Multiple columns
filtered = df[df['age'] > 30]       # Filtering rows

# Data cleaning
df_clean = df.dropna()              # Remove rows with missing values
df['age'].fillna(df['age'].mean())  # Fill missing with mean

# Grouping (like SQL GROUP BY)
avg_salary_by_city = df.groupby('city')['salary'].mean()

# Creating new columns
df['salary_in_k'] = df['salary'] / 1000


   age  salary city
0   25   50000  NYC
1   30   60000   SF
2   35   70000   LA
3   40   80000  NYC
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   age     4 non-null      int64 
 1   salary  4 non-null      int64 
 2   city    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None
             age        salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [12]:
# Scikit-learn workflow (THIS IS THE PATTERN YOU'LL USE ALWAYS)

# Step 1: Prepare data
X = df[['age', 'salary']]  # Features
y = df['city']              # Target

# Step 2: Split data (more on this later)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train ",X_train)
print("X_test ",X_test)
print("y_train ",y_train)
print("y_test ",y_test)
# Step 3: Create and train model
model = DecisionTreeClassifier()
print("model ",model)
model.fit(X_train, y_train)  # Learning happens here!

# Step 4: Make predictions
predictions = model.predict(X_test)
print("predictions ",predictions)

# Step 5: Evaluate
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy}")


X_train     age  salary
1   30   60000
0   25   50000
3   40   80000
X_test     age  salary
2   35   70000
y_train  1     SF
0    NYC
3    NYC
Name: city, dtype: object
y_test  2    LA
Name: city, dtype: object
model  DecisionTreeClassifier()
predictions  ['SF']
Accuracy: 0.0
