What is numpy ?
Numpy is python lib used to work with numbers, arrays to perform mathematical operations efficiently. It gives fast numberical computation (faster than python list), powerful multi-dimemsional array(NDarray), tools for linear algebra, stats, random numbers

It is fast because it uses optimized C backend. Operation on array happens at once, much faster then python loops. 

Example: adding 2 list in python (slow loop)
Adding 2 numpy arrays (vectorized, extremely fast)

All ML models uses matrices, vectors, linear algebra, matrix multiplication, dot products. Numpy handles all the efficiently

All major libs uses numpy, like pands, scikiet-leawrn takes numpy arrays as input, pytorch and tensorFlow uses numpy operations

In [2]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10,11])



In [9]:
arr1+=1
arr2*=2
print("Array 1 after addition:", arr1)
print("Array 2 after multiplication:", arr2)


Array 1 after addition: [2 3 4 5 6]
Array 2 after multiplication: [12 14 16 18 20 22]


In [10]:
##since array are of different shapes, broadcasting will fail here a
## is of size (5,), while arr2 is of size (6,)
arr3=arr1+arr2
print("Resultant Array after addition:", arr3)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [11]:
arr3=arr1+arr2[:5]
print("Resultant Array after addition:", arr3)

Resultant Array after addition: [14 17 20 23 26]


In [12]:
print(arr1.shape)
print(arr2.shape)

(5,)
(6,)


In [13]:
print(arr1.reshape(5, 1))
print("--------------------------")
print(arr2.reshape(1, 6))
print("--------------------------")
arr3=arr1.reshape(5, 1) + arr2.reshape(1, 6)
#arr3=arr1+arr2
print(arr3)
#print("Element-wise addition:", arr3)

[[2]
 [3]
 [4]
 [5]
 [6]]
--------------------------
[[12 14 16 18 20 22]]
--------------------------
[[14 16 18 20 22 24]
 [15 17 19 21 23 25]
 [16 18 20 22 24 26]
 [17 19 21 23 25 27]
 [18 20 22 24 26 28]]


array creation
np.linspace() generates evenly spaced numbers between a start and end value.
Why it's useful:
Used in ML & Data Science for plotting graphs
Creating smooth ranges
Creating sample data
Creating equally distributed values

np.eye(3): Identity matrix is like the number 1 in matrices.Multiplying a matrix A × I = A
Used heavily in:
Linear algebra
Inverse matrix checks

In [15]:
zeroes=np.zeros((3,3))               # matrix of zeros
ones=np.ones((2,2))                # matrix of ones
like_range=np.arange(0, 10, 2)           # like range()
linspace_op=np.linspace(0, 1, 5)          # 5 values between 0 and 1
print("Zeros:\n", zeroes)
print("Ones:\n", ones)
print("Arange:\n", like_range)
print("Linspace:\n", linspace_op)
np.eye(3) 

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Arange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Size, shape, datatype inspection

In [16]:
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)


1
5
int64


slicing

In [19]:
print(arr1[0])            # first element
print(arr1[1:4])          # slicing

2
[3 4 5]


math operations

In [21]:
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.percentile(arr1, 90))

4.0
4.0
1.4142135623730951
2.0
2
6
5.6


6. Linear Algebra
np.dot(a, b)        # dot product
np.matmul(a, b)     # matrix multiplication
np.linalg.inv(A)    # inverse matrix
np.linalg.det(A)    # determinant
np.linalg.eig(A)    # eigenvalues

Random module

In [22]:
np.random.rand(3, 3)
np.random.randint(0, 10, 5)
np.random.randn(4, 4)
np.random.seed(42)  

Reshaping

In [26]:
#arr1.reshape(3, 4)
print(arr1.ravel())         # flatten
arr1.T               # transpose


[2 3 4 5 6]


array([2, 3, 4, 5, 6])